### ISSUE TITLE
Video of Verse connecting many instances of LoqAirou in different operational systems. (Resource for the readme file).

### ISSUE THREAD

**Issue by chicortiz** [Gages/verse_apps#2]
Hello Warren!

Sorry for the fork. I already deleted it. I was trying to edit the Readme.md file to add this video as an illustration of "verse" working to connect many instances of LoqAirou 1, on different operational systems:

 Verse protocol server and LoqAirou working under Windows, Linux and MacOSX
(YouTube Video).

https://youtu.be/wNdqMdjFrrk

**Comment by Gages** [comment]
The fork is totally fine! It's open source after all. I believe you can fork-and-pull-request, which will allow me to quickly accept your changes.

Thank you for these videos. I have references to them [in the Wiki](https://github.com/Gages/verse_apps/wiki/Loq-Airou-Demonstrations) and linked to them from the README file. At this time I don't want to put them in the README as I feel that it might be too long already. Also, I don't want to mislead - there may be stability issues with the code in this repository, and I don't want to false advertise!

**Comment by chicortiz** [comment]
Thank you so much for adding this video to the Wiki Warren. It's a honour. :)
