### ISSUE TITLE
Video montage of two architects using LoqAirou for 3D modelling. (Resource for the readme file). 

### ISSUE THREAD

**Issue by chicortiz** [Gages/verse_apps#3]
Three clients:

Left: Quelsolaar rendering engine 1.

Right side, above: Architect "A" using LoqAirou 1.

Right side, below:  Architect "B" using LoqAirou 1.

Intent: illustration for the Readme.Md file of this repository.

You tube video "Synchrony":
https://youtu.be/yMvjg-r9XVM

**Comment by Gages** [comment]
Commented on this other issue:

#2

**Comment by chicortiz** [comment]
Thank you very much.
