### ISSUE TITLE
Ubuntu Tutorial: Stuck on "Part 2: Running Loq Airou:"

### ISSUE THREAD

**Issue by chicortiz** [Gages/verse_apps#6]
Hello Warren. 

I'm stuck on step 3 of your tutorial for Ubuntu installation.

The terminal is returning the following:

chico@note-lg:~$ build-default/artefacts/bin/verse_server
bash: build-default/artefacts/bin/verse_server: Arquivo ou diretório não encontrado

"Arquivo ou directório não encontado" stands for "File or directory not found".

At the moment I'm working to set my terminal to return stuff in English.

# # #

Additional details:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Edit:
O great!
"export LC_ALL=C"
Sets the terminal "output" (<---? Is this the correct term?) to English.

**Comment by chicortiz** [comment]
Tried again today, problem remains. 
"File or directory not found"

**Comment by Gages** [comment]
Did you complete the "building verse apps" step? File not found means that the build has not completed. The build-default/artefacts/bin directory should contain the outputs of the tup command.

**Comment by Gages** [comment]
I have added further explanation to the build steps. I hope that can help you.

**Comment by chicortiz** [comment]
Hi @Gages!  Thank you.

Here is what I can read in my terminal:

chico@note-lg:~$ git clone https://github.com/Gages/verse_apps.git
fatal: destination path 'verse_apps' already exists and is not an empty directory.
chico@note-lg:~$ cd verse_apps
chico@note-lg:~/verse_apps$ tup variant tupconf/default.config
tup error: Variant directory 'build-default' already exists and is not empty.
chico@note-lg:~/verse_apps$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [1.419s] Reading in new environment variables...
[ tup ] [1.420s] No Tupfiles to parse.
[ tup ] [1.420s] No files to delete.
[ tup ] [1.421s] No commands to execute.
[ tup ] [1.421s] Updated.
chico@note-lg:~/verse_apps$ 

Does that mean that the "Part 1: Building Verse Apps" is complete?

**Comment by Gages** [comment]
Hi again!

I can't tell which step in the process has gone wrong. It looks like you are trying to run the process twice. In this case you should remove the build-default directory and try again from this step: `tup variant tupconfg/default.config`. which creates the build-default directory for you.

I have made a video at the bottom of the installation instructions to show what it looks like successfully. Maybe that will help you work it out.

Well done for perseverance 🥇

**Comment by chicortiz** [comment]
Solution:

https://github.com/Gages/verse_apps/issues/14
